Repository sirateek/ta-assistant-cli, pull requests merged in 2020-12, with the labels that each got.

#1 [New Feature] Add Path Validation Feature
  .gitignore
  core/main.py
Labels: Feature

#2 [New Feature] Add Count Work Feature
  core/job_list/job_list.py
  core/main.py
  example_dir/ex1/6310546062_vitvara_ex1.zip
  example_dir/ex1/6310546063_vitvara_ex1.zip
  example_dir/ex1/6310546064_vitvara_ex1.zip
  example_dir/ex1/6310546065_vitvara_ex1.zip
  example_dir/ex1/6310546066_vitvara_ex1.zip
  example_dir/ex1/ta/job/job.json
Labels: Feature

#4 [Update] Add Flexibllity of reading file
  core/job_list/job_list.py
  core/main.py
  example_dir/ex1/Unknown File.zip
Labels: Feature

#8 Add test case for core/job_list/job_list.py
  core/job_list/test_job_list.py
Labels: Repo, Test

#12 [Test] Add Test For `recover app state`
  core/job_list/job_list.py
  core/job_list/test_job_list.py
  core/main.py
Labels: Test

#15 [Feature] Add process 4 - ask user to accept the loaded job list
  core/display_module/display_module.py
  core/display_module/menu.py
  core/job_list/job_list.py
  core/main.py
Labels: Feature, enhancement

#16 [Feature] Add `FileManager` Module
  .gitignore
  core/file_manager_module/file_manager.py
  core/file_manager_module/test_file_manager.py
  example_dir/ex1/ta/draft/draft.json
  test/test_file_manager/Test.zip
Labels: Feature, enhancement

#17 [Refactor] Refactor the JobList Object
  core/job_list/job_list.py
  core/job_list/test_job_list.py
  core/main.py
Labels: enhancement
